import {
  Activity,
  Archive,
  Boxes,
  Database,
  History,
  Rocket,
  Settings,
  WandSparkles,
} from "lucide-react";

export const copy = {
  zh: {
    app: "LocalTune Console",
    sub: "本地大模型微调控制中心",
    workspace: "工作台",
    overview: "总览",
    overviewHint: "汇总当前训练、语料、模型和产物，优先呈现需要处理的信息。",
    corpus: "语料管理",
    models: "模型管理",
    training: "训练执行",
    artifacts: "训练产出",
    artifactsHint: "管理最终 LoRA Adapter 和 Checkpoint，并查看它们对应的训练来源。",
    inference: "推理验证",
    history: "任务中心",
    environment: "系统环境",
    refresh: "刷新",
    open: "打开",
    openFolder: "打开文件夹",
    status: "任务状态",
    monitor: "运行监控",
    existingCorpus: "已有语料",
    createCorpus: "生成新语料",
    deriveTrainableCorpus: "派生训练语料",
    formatGuide: "格式说明",
    corpusHint: "管理训练语料集、原始素材和样本检查结果。训练页只引用这里准备好的训练语料集。",
    deriveHint: "只从已经结构化、可训练的 JSONL 语料复制、截取或抽样生成新文件，适合小批量试跑或训练集切片。",
    trainingHint: "启动前先确认基础模型、加载方式、训练语料集和关键训练参数。下方监控区会持续刷新日志、loss 和资源占用。",
    needSelectModel: "请选择基础模型",
    needValidModelPath: "模型路径不可用",
    needSelectDataset: "请选择训练语料集",
    needValidDataset: "训练语料集未通过检查",
    needOutputDir: "缺少输出目录",
    trainingAlreadyRunning: "已有训练正在运行",
    error_TRAINING_ALREADY_RUNNING: "已有训练正在运行。请先在训练执行页查看当前任务，等待完成或手动停止后再启动新任务。",
    error_BASE_MODEL_REQUIRED: "还没有选择基础模型。请到模型管理添加并扫描本地模型目录，然后在训练执行页选择可训练模型。",
    error_DATASET_PROFILE_REQUIRED: "还没有选择训练语料集。请到语料管理创建或选择包含训练集的 JSONL 训练语料集。",
    error_CHECKPOINT_INVALID: "选择的 checkpoint 不可用。请从训练产物页选择存在的 checkpoint 目录，或取消恢复训练。",
    error_BRANCH_BACKEND_UNSUPPORTED: "当前加载方式不支持本机计算后端。当前公开版本的已验证微调路线需要 NVIDIA CUDA + bnb4/NF4 QLoRA。",
    error_BRANCH_UNSUPPORTED: "当前加载方式不是 LocalTune 支持的微调路线。请使用 bnb4/NF4 QLoRA，NVFP4 不作为当前微调入口。",
    error_MODEL_DIRECTORY_UNRECOGNIZED: "这个目录不是可训练的基础模型目录。请选择包含 config、tokenizer 和 safetensors/bin 权重的 Transformers 模型目录；GGUF 不能作为微调输入。",
    error_MODEL_BRANCH_UNSUPPORTED: "当前模型格式没有兼容的微调加载方式。请确认模型是 Transformers 兼容格式，并在模型管理查看模型格式，在系统环境查看训练支持范围。",
    error_MODEL_NOT_FOUND: "模型列表中没有这条记录，刷新页面后再试。",
    error_OUTPUT_DIR_REQUIRED: "训练输出目录还没有配置。请在配置文件中设置 training.output_dir，或重新生成本机配置。",
    error_VALIDATION_ERROR: "提交内容不符合要求。请检查当前输入框附近的提示；如果是路径，请确认目录真实存在且格式正确。",
    error_TRAINING_START_FAILED: "训练没有启动成功。请先查看快速开始的当前状态，再检查系统环境、模型路径、训练语料集和任务日志。",
    error_REQUEST_FAILED: "操作失败，请稍后重试。",
    trainingLaunch: "启动训练",
    basicSetup: "基础选择",
    trainingScale: "训练规模",
    loraAndSaving: "LoRA 与保存",
    safetyOptions: "加载策略",
    selectModel: "请选择模型",
    modelPath: "模型路径",
    modelPathMissing: "模型路径缺失",
    trainingMonitoring: "训练监控",
    trainingMonitoringHint: "训练启动后在这里查看任务状态、loss 曲线、资源占用和日志。",
    trainingTrace: "训练上下文",
    noTrainingTrace: "等待训练任务",
    waitingForTrainingTask: "等待训练任务",
    trainingTraceEmptyHint: "启动训练后，这里会展示本次任务使用的模型、语料、运行配置和输出位置。",
    trainingTraceShowsConfig: "基础模型、加载方式、训练语料集和运行配置",
    trainingTraceShowsOutputs: "输出目录以及本次训练记录到的产物",
    noActiveTrainingTask: "当前没有训练任务",
    startTrainingToMonitor: "启动训练后，这里会显示当前任务的状态和关键字段。",
    noActiveTrainingLogs: "当前没有运行中的训练，日志区域不会显示历史任务内容。",
    recordedArtifacts: "已记录产物",
    noRecordedArtifactsYet: "当前训练尚未记录产物。训练完成后会自动记录最终 LoRA Adapter 和 Checkpoint。",
    postTrainingActions: "完成后操作",
    postTrainingActionsHint: "基于这次训练继续查看产物、验证效果或复用参数再跑。",
    viewArtifacts: "查看本次产物",
    validateFinalAdapter: "验证最终 LoRA Adapter",
    rerunTask: "复用参数再跑",
    noRerunParams: "缺少可复用参数",
    exportRecipe: "导出 Recipe",
    openRecipe: "打开 Recipe",
    selectRecipe: "选择训练 Recipe",
    applyRecipe: "应用 Recipe",
    envHint: "查看工程位置、服务配置和本机依赖状态。",
    modelsHint: "管理本地基础模型目录，扫描后把可用模型加入训练选择列表。",
    goldenRun: "快速开始",
    goldenRunNav: "快速开始",
    goldenRunHint: "大模型微调很简单，带你快速完成首次微调。",
    quickStartSidebarHint: "完成首次本地微调",
    quickStartPending: "{count} 个待处理项",
    quickStartNext: "下一步：{step}",
    quickStartDone: "首次试运行已完成",
    continueQuickStart: "继续快速开始",
    quickStartOverviewTitle: "按推荐流程跑通首次试运行训练",
    quickStartOverviewHint: "优先完成环境、基础模型、训练语料和试运行训练，之后再进入日常工作台。",
    viewQuickStart: "查看快速开始",
    goldenLoading: "正在加载快速开始...",
    goldenStartSmoke: "启动试运行训练",
    goldenFixNextStep: "处理下一步",
    goldenPathTitle: "首次微调路径",
    goldenPathHint: "按这个顺序补齐条件；当前需要处理的环节会高亮显示。",
    goldenStartupChecklist: "启动前检查",
    goldenStartupChecklistHint: "按训练启动所需条件排列；只要有一项缺失，启动按钮就保持不可用。",
    goldenChecklistItem: "检查项",
    goldenChecklistStatus: "状态",
    goldenChecklistDetail: "说明",
    goldenChecklistAction: "操作",
    goldenTestRunConfig: "本次试运行配置",
    goldenTestRunConfigHint: "条件满足后会使用这组配置启动训练。",
    goldenAfterFixTitle: "补齐后会发生什么",
    goldenAfterFixStep1: "快速开始页会自动刷新检查结果。",
    goldenAfterFixStep2: "启动按钮变为可用，执行一次短训练。",
    goldenAfterFixStep3: "训练日志、Loss 和产物进入对应页面。",
    goldenMissingBaseModelShort: "尚未选择",
    goldenReadinessScore: "快速开始就绪分数",
    goldenReadiness: "就绪度",
    goldenNext: "下一步",
    goldenRecommendedAction: "建议下一步",
    goldenSelectStepHint: "选择一段路径查看当前状态。",
    goldenStatus_done: "已完成",
    goldenStatus_ready: "可开始",
    goldenStatus_blocked: "待准备",
    goldenStep_golden: "快速开始",
    goldenStep_environment: "环境检查",
    goldenStep_model: "基础模型",
    goldenStep_dataset: "训练语料",
    goldenStep_smoke: "试运行训练",
    goldenStep_train: "正式训练",
    goldenStep_evaluate: "推理评估",
    goldenStepDetail_environment_done: "核心依赖、加速后端和运行环境已满足首次训练要求。",
    goldenStepDetail_environment_blocked: "请在系统环境中检查 Python、计算设备后端和核心依赖。",
    goldenStepDetail_environment_ready: "环境检查可以继续完善。",
    goldenStepDetail_model_done: "已有可用基础模型。",
    goldenStepDetail_model_blocked: "请添加本地模型目录，扫描后把识别到的模型加入模型列表。",
    goldenStepDetail_model_ready: "选择可用于本次训练的基础模型。",
    goldenStepDetail_dataset_done: "已有通过校验的训练语料集。",
    goldenStepDetail_dataset_blocked: "请导入 JSONL 训练语料，创建训练语料集并通过格式检查。",
    goldenStepDetail_dataset_ready: "选择一份训练语料集用于首次训练。",
    goldenStepDetail_smoke_done: "最近一次试运行训练已经完成。",
    goldenStepDetail_smoke_ready: "检查试运行参数并运行 1 步训练，验证模型加载、语料读取、loss 和产物关联。",
    goldenStepDetail_smoke_blocked: "先完成环境、模型和语料准备。",
    goldenStepDetail_train_done: "已有可用于后续验证的 Adapter。",
    goldenStepDetail_train_ready: "试运行训练已通过，可以把参数提升为正式训练。",
    goldenStepDetail_train_blocked: "先跑通试运行训练，再进入正式训练。",
    goldenStepDetail_evaluate_done: "已有完成的评估记录。",
    goldenStepDetail_evaluate_ready: "使用 Base / Adapter 对比验证最终效果，并保存报告。",
    goldenStepDetail_evaluate_blocked: "训练完成并生成 Adapter 后再进行评估。",
    goldenAction_golden: "检查整体就绪状态",
    goldenAction_environment: "修复环境配置",
    goldenAction_model: "添加或选择基础模型",
    goldenAction_dataset: "导入训练语料",
    goldenAction_smoke: "启动试运行训练",
    goldenAction_train: "启动正式训练",
    goldenStartFormal: "启动正式训练",
    goldenAction_evaluate: "验证 Adapter 效果",
    goldenBlockers: "待处理事项",
    goldenBlocker_environment: "环境尚未就绪：请检查核心依赖、加速后端和运行环境。",
    goldenBlocker_model: "还没有可用的本地基础模型，请先在模型管理中添加并扫描模型目录。",
    goldenBlocker_dataset: "还没有通过校验的训练语料集，请先导入 JSONL 训练语料。",
    goldenSuccessMetrics: "首次训练检查",
    goldenSuccessMetricsHint: "确认本次流程是否已经具备可训练、可观察、可验证的关键结果。",
    goldenMetricTime: "评估 Adapter 用时",
    goldenMetricTimeHint: "首次完成后开始记录",
    goldenMetricSmoke: "试运行成功",
    goldenMetricSmokeHint: "模型加载、语料读取和 loss",
    goldenMetricData: "语料质量",
    goldenMetricDataHint: "已校验的训练语料集",
    goldenMetricEvaluation: "评估就绪",
    goldenMetricEvaluationHint: "基础模型 / Adapter 对比报告",
    goldenMetricValuePending: "待验证",
    goldenMetricValueReady: "已就绪",
    goldenMetricValueWaitingAdapter: "等待 Adapter",
    goldenMetricValueNotMeasured: "尚未记录",
    goldenRunCapsule: "运行胶囊",
    goldenRunCapsuleHint: "首次训练的可复用上下文",
    goldenWaitingForTraining: "等待训练完成",
    goldenSmokeRecipe: "试运行 Recipe",
    goldenSmokeRecipeHint: "首次证明链路可用的安全默认值",
    goldenRunSmoke: "运行试运行训练",
    goldenPromote: "提升为正式训练",
    goldenLastChecked: "最后检查",
    goldenLocalOnly: "仅展示本机状态；本页面不会上传语料、模型或训练产物。",
    goldenTrainabilityLabel: "当前状态",
    goldenModelGuidanceLabel: "模型选择建议",
    goldenModelGuidanceTitle_ready: "优先选择显存余量更充足的基础模型",
    goldenModelGuidanceTitle_unknown: "还不能判断合适的模型规模",
    goldenModelGuidanceTitle_not_supported: "当前硬件暂不支持微调入口",
    goldenModelGuidance_ready: "当前 {device} 约 {vram} 显存；建议优先选择不超过 {recommended} 的 bnb4/NF4 QLoRA 模型，接近 {caution} 时请先跑试运行训练。",
    goldenModelGuidance_unknown: "平台暂时无法读取可用显存。添加模型后仍会尽量从目录名和配置中识别参数规模，并给出保守提示。",
    goldenModelGuidance_not_supported: "当前训练入口需要 NVIDIA CUDA。你仍可以管理语料和模型，但不建议期待本机跑出微调结果。",
    goldenModelGuidanceAction: "管理基础模型",
    recommendedModelsLabel: "基于当前设备环境推荐",
    recommendedModelsTitle: "推荐模型列表",
    recommendedModelsHint: "检测到 {device}，可用显存约 {vram}。",
    loadingModelRecommendations: "正在生成模型推荐...",
    recommendedMinVram: "建议显存",
    recommendedProvider: "下载来源",
    recommendedModelFit_recommended: "推荐",
    recommendedModelFit_caution: "可试跑",
    recommendedModelFit_too_large: "不建议",
    recommendedModelFit_unknown: "待确认",
    recommendedModelFit_unsupported: "暂不可训",
    openDownloadPage: "打开下载页",
    copyDownloadCommand: "复制命令",
    startDownload: "开始下载",
    cancelDownload: "取消下载",
    copied: "已复制",
    downloadDependencyMissing: "缺少下载依赖",
    downloadDependencyMissingHint: "可先复制命令，或重新运行启动脚本安装可选依赖。",
    downloadStatus_running: "下载中",
    downloadStatus_stopping: "正在停止",
    downloadStatus_completed: "下载完成",
    downloadStatus_missing: "文件已移除",
    downloadStatus_failed: "下载失败",
    downloadStatus_cancelled: "已取消",
    goldenReadiness_ready_title: "当前机器可以启动试运行训练",
    goldenReadiness_ready_detail: "环境、基础模型和训练语料都已就绪。建议先跑 1 step 试运行训练，确认模型加载、语料读取、loss 和产物关联正常。",
    goldenReadiness_ready_action: "启动试运行训练",
    goldenReadiness_running_title: "已有训练正在运行",
    goldenReadiness_running_detail: "当前机器正在执行训练任务。请进入训练执行页查看日志、loss 和资源占用，等待完成或手动停止后再启动新任务。",
    goldenReadiness_running_action: "查看训练执行",
    goldenReadiness_unsupported_backend_title: "当前硬件暂不能微调",
    goldenReadiness_unsupported_backend_detail: "当前公开版本的已验证微调路线需要 NVIDIA CUDA。非 CUDA 设备可以查看项目和语料，但不要期待跑出微调结果。",
    goldenReadiness_unsupported_backend_action: "查看系统环境",
    goldenReadiness_missing_environment_title: "环境还没达到训练要求",
    goldenReadiness_missing_environment_detail: "请先检查 Python、CUDA、PyTorch、bitsandbytes 和前端工具链。系统环境页会展示缺失项和当前计算后端。",
    goldenReadiness_missing_environment_action: "查看系统环境",
    goldenReadiness_missing_model_title: "还没有可训练的基础模型",
    goldenReadiness_missing_model_detail: "请到模型管理添加本地模型目录并扫描。当前训练入口需要 Transformers 兼容的基础模型目录，GGUF 不能作为微调输入。",
    goldenReadiness_missing_model_action: "添加基础模型",
    goldenReadiness_missing_dataset_title: "还没有可用训练语料",
    goldenReadiness_missing_dataset_detail: "请导入或选择 JSONL 训练语料，并创建包含训练集的训练语料集。格式检查通过后才能启动训练。",
    goldenReadiness_missing_dataset_action: "准备训练语料",
    noData: "暂无数据",
    noArtifactsYet: "完成一次试运行或正式训练后，这里会出现 LoRA Adapter、Checkpoint 或完整模型。",
    noMatchingDatasetProfiles: "没有匹配的训练语料集",
    noMatchingMaterials: "没有匹配的原始素材",
    start: "启动训练",
    stop: "停止",
    runInference: "运行推理",
    selectAdapter: "请选择 Adapter",
    needSelectAdapter: "请选择用于验证的 Adapter",
    inferenceHint: "使用 final adapter 对训练效果做一次真实推理验证。",
    inferenceSetup: "验证设置",
    singleInference: "单条验证",
    baseAdapterCompare: "Base / Adapter 对比",
    batchValidation: "批量验证",
    datasetSplit: "数据集划分",
    sampleCount: "样本数量",
    systemPrompt: "系统提示词",
    maxInputTokens: "最大输入 token",
    stopWords: "停止词",
    stopWordsHint: "多个停止词用逗号分隔",
    baseModelOutput: "基础模型输出",
    adapterOutput: "Adapter 输出",
    expectedOutput: "预期输出",
    evaluationReport: "评估报告",
    runBatchValidation: "运行批量验证",
    openReport: "打开报告",
    jsonReport: "JSON 报告",
    markdownReport: "Markdown 报告",
    waitingInferenceOutput: "等待推理输出...",
    running: "运行中",
    idle: "空闲",
    completed: "已完成",
    failed: "失败",
    checking: "检查中",
    valid: "可用",
    invalid: "不可用",
    activeCorpus: "当前语料",
    corpusLibrary: "语料库",
    selectCorpus: "选择语料",
    datasetFiles: "个语料文件",
    rawMaterialsExcluded: "个原始素材未列入",
    trainableCorpus: "训练语料",
    trainableCorpusFiles: "JSONL 文件",
    readyTrainingDatasets: "可用训练语料集",
    trainingDatasetInventoryHint: "训练页只选择训练语料集；训练集存在且格式检查通过才算可用。",
    trainingDatasetInventoryEmpty: "还没有训练语料集，请先到语料管理准备 JSONL 数据。",
    trainingDatasets: "训练语料集",
    trainingDatasetsHint: "训练语料集是训练执行引用的数据单位；每份语料集包含训练集、验证集和测试集。",
    selectTrainingDataset: "选择训练语料",
    rawMaterials: "原始素材",
    rawMaterial: "原始素材",
    materialFiles: "个素材文件",
    selectMaterial: "选择素材",
    materialFile: "素材文件",
    materialHint: "原始素材用于阅读、定位和来源追踪。",
    trainableCorpusHint: "{files} 个 JSONL 文件可被训练语料集引用；当前有 {profiles} 个训练语料集用于训练执行，另有 {materials} 个原始素材已分离管理。",
    datasetProfileInventory: "训练语料集统计",
    datasetProfileAlignmentHint: "训练执行选择的是训练语料集；每个训练语料集引用一组训练集、验证集和测试集 JSONL 文件。",
    materialInfo: "素材信息",
    materialProperties: "素材属性",
    materialPropertiesHint: "按文件资产维度展示，不按训练样本结构解析。",
    materialPreview: "素材预览",
    materialPreviewHint: "显示可读取的文本片段，用于快速确认内容。",
    materialUsage: "用途",
    materialUsageHint: "可作为人工制作语料时的参考来源。",
    sourcePreview: "原文预览",
    contentPreview: "内容预览",
    fileType: "文件类型",
    datasetComposition: "语料组成",
    datasetSplitGroupTitle: "训练集 / 验证集 / 测试集",
    datasetCompositionHint: "训练执行会使用这一组训练集、验证集和测试集文件。",
    selectDatasetProfileToInspect: "请选择一份训练语料查看组成。",
    missingSplitHint: "该集合缺失，暂无样本可预览。",
    splitFromTrain: "从训练集摘取验证/测试集",
    splitFromTrainHint: "会生成新的训练集、验证集和测试集文件，并回写到所选训练语料集。",
    createMissingSplits: "生成缺失集合",
    missingSplits: "缺失：{roles}",
    valRatio: "验证集比例",
    testRatio: "测试集比例",
    seed: "随机种子",
    trainDataRequired: "需要先有可用训练集。",
    previewSamples: "预览样本",
    ready: "已就绪",
    notReady: "未就绪",
    validation: "校验状态",
    commonProperties: "共性属性",
    corpusFile: "语料文件",
    filePath: "文件路径",
    folder: "所在目录",
    sampleRows: "样本行数",
    trainable: "可训练",
    formatCheck: "格式检查",
    samplePreview: "样本预览",
    loadingCorpusSamples: "正在加载语料样本...",
    searchSamples: "搜索样本内容",
    sampleRange: "第 {start}-{end} 条，共 {total} 条",
    previousPage: "上一页",
    nextPage: "下一页",
    overwriteDerivedFileTitle: "覆盖派生文件",
    overwriteDerivedFileConfirm: "目标文件已存在，确定覆盖吗？此操作不可撤销。",
    artifactCount: "训练产出",
    latestLoss: "最新 loss",
    currentTraining: "当前训练",
    latestTraining: "最近一次训练",
    noTrainingHistory: "还没有训练记录",
    startTraining: "开始训练",
    enterTrainingPage: "进入训练执行",
    overviewNoActiveTraining: "当前没有运行中的训练。需要启动新训练时，请进入训练执行页确认基础模型、训练语料集和参数。",
    viewTraining: "查看训练",
    viewTaskDetails: "查看任务详情",
    taskLoss: "本次训练 Loss",
    metricPoints: "个指标点",
    fromFirstStep: "相较第一个记录点",
    lossBelongsToTask: "仅展示当前任务数据",
    firstValue: "初始",
    latestValue: "最新",
    attentionItems: "待处理事项",
    attentionSummary: "{count} 类问题需要处理",
    noAttentionItems: "当前没有需要处理的问题",
    allProfilesReady: "全部训练语料集可用",
    profilesNeedAttention: "部分训练语料集需要处理",
    noDatasetProfiles: "还没有训练语料集",
    usableModels: "可用基础模型",
    readyForInference: "可加载到基础模型进行推理",
    noDeployableAdapters: "暂无 LoRA Adapter",
    invalidProfilesIssue: "{count} 个训练语料集不可用",
    noDatasetProfilesIssue: "还没有可用于训练的训练语料集",
    noUsableModelsIssue: "没有可用的基础模型",
    invalidAdaptersIssue: "{count} 个 Adapter 检查未通过",
    failedTasksIssue: "最近有 {count} 个训练任务失败",
    unlinkedArtifactsIssue: "{count} 个历史产物缺少精确训练来源",
    sourceMissing: "缺少训练来源",
    recentTrainingTasks: "最近训练任务",
    recentTrainingTasksHint: "最近五次训练及其状态、语料和产出",
    recentArtifacts: "最近训练产出",
    recentArtifactsHint: "最近生成的 Adapter 和训练检查点",
    viewAll: "查看全部",
    systemResources: "系统资源",
    systemResourcesHint: "当前 CPU、内存和 GPU 状态；训练运行时持续更新",
    loss: "Loss 曲线",
    noLossData: "暂无 loss 数据",
    singleLossHint: "只有一个点时无法形成趋势线",
    rowsUnit: "行",
    samplesUnit: "条样本",
    previewRowsUnit: "预览行",
    cpu: "CPU",
    memory: "内存",
    gpuMemory: "GPU 显存",
    gpuUtil: "GPU 利用率",
    gpuTemperature: "GPU 温度",
    gpuTemperatureHint: "温度数据由硬件监控后端提供",
    gpuPower: "GPU 功耗",
    notAvailable: "当前不可用",
    taskLogs: "任务日志",
    trainingStep: "训练进度",
    trainingSpeed: "训练速度",
    eta: "预计剩余",
    epoch: "Epoch",
    searchLogs: "搜索日志",
    allLogs: "全部",
    metricLogs: "训练指标",
    warningLogs: "警告",
    errorLogs: "错误",
    followLogs: "跟随最新",
    jobId: "任务 ID",
    mode: "运行模式",
    trainingPlan: "训练方案",
    trainingPlanHint: "先选择训练意图，系统会同步套用语料偏好、步数、日志和保存策略。",
    smokePlan: "试运行检查",
    smokePlanHint: "只验证模型加载、语料读取、loss 和产物链路，不用于效果判断。",
    smokePlanPreset: "固定 20 步 · 每步记录 · 第 20 步保存",
    smokeDatasetPolicy: "优先使用小样本训练语料集",
    fullPlan: "正式训练",
    fullPlanHint: "用于生成可长期使用的 LoRA Adapter，使用完整训练配置。",
    fullPlanPreset: "使用完整语料 · 训练步数按配置设置",
    fullDatasetPolicy: "优先使用完整训练语料集",
    branch: "加载方式",
    dataset: "训练语料集",
    started: "开始时间",
    finished: "结束时间",
    timeRange: "运行时间",
    log: "日志",
    smoke: "试运行",
    full: "正式",
    formal: "正式",
    maxSteps: "最大步数",
    maxSeqLength: "最大序列长度",
    loraR: "LoRA 秩",
    gradAccumulation: "梯度累积",
    loggingSteps: "日志步频",
    saveSteps: "保存步频",
    resumeFromCheckpoint: "训练起点",
    startFromBaseModel: "新训练：从基础模型开始",
    continueFromCheckpoint: "继续训练",
    disableFallbackChain: "只使用所选加载方式",
    loadingStrategyHint: "开启后，本次训练会严格使用上面选择的加载方式；如果环境不匹配，会直接报错，不会自动切换到其它方式。",
    currentComputeBackend: "当前计算后端",
    supportedComputeBackends: "支持后端",
    backendUnsupported: "当前计算后端不支持该加载方式",
    useConfig: "留空使用默认值",
    useDefaultValue: "留空使用默认值",
    source: "来源",
    sourceDataset: "训练语料来源",
    output: "输出",
    deriveMode: "生成方式",
    limit: "数量上限",
    head: "前 N 条",
    tail: "后 N 条",
    sample: "随机抽样",
    copy: "复制全部",
    generateFile: "生成文件",
    generateDerivedFile: "生成派生文件",
    deriveBoundaryTitle: "仅处理训练语料",
    deriveBoundaryHint: "这里不会读取原始素材；输入必须是已经可训练的 JSONL 文件。",
    noTrainableCorpus: "暂无可派生的训练语料",
    datasetProfiles: "训练语料集",
    datasetProfilesHint: "训练启动时会选择一个训练语料集。这里集中查看训练集、验证集、测试集文件、行数和校验状态。",
    addTrainingDataset: "添加训练语料集",
    importTrainingCorpus: "从文件创建训练语料集",
    importTrainingCorpusDone: "已导入 {name}，并创建训练语料集",
    createDatasetProfile: "新建空训练语料集",
    editDatasetProfile: "编辑训练语料集",
    copyDatasetProfile: "复制训练语料集",
    deleteDatasetProfileTitle: "删除训练语料集",
    deleteDatasetProfileConfirm: "确定删除训练语料集“{name}”吗？语料文件本身不会被删除。",
    datasetProfileEditorHint: "训练语料集用于组织训练集、验证集和测试集；删除语料集不会删除原始语料文件。",
    datasetProfileFileHint: "训练集必选，验证集和测试集可以留空后再从训练集摘取。",
    profileIdentity: "语料集信息",
    profileId: "语料集 ID",
    name: "名称",
    description: "说明",
    edit: "编辑",
    delete: "删除",
    confirmDelete: "确认删除",
    confirmRemove: "确认移除",
    confirmOverwrite: "确认覆盖",
    save: "保存",
    cancel: "取消",
    notSelected: "未选择",
    validationPassed: "检查通过",
    validationFailed: "检查失败",
    validationSummary: "{errors} 个错误，{warnings} 个警告",
    revalidate: "重新校验",
    selectedDatasetProfile: "本次训练语料集",
    selectDatasetProfile: "请选择训练语料集",
    currentTrainingDataset: "训练语料集",
    searchDatasets: "搜索训练语料集",
    datasetStatus: "状态",
    readyToTrain: "可以开始训练",
    readyToTrainHint: "训练集已就绪，验证集通过检查；测试集缺失不会阻塞训练。",
    readyForTrialRun: "可以试跑",
    notReadyToTrain: "暂不能训练",
    notReadyToTrainHint: "请先补齐训练集并通过格式检查。",
    trainingDatasetMissingTrainHint: "请先配置训练集并通过格式检查。",
    trainingDatasetValidationFailedHint: "语料格式检查未通过，请先查看并修复问题。",
    trainingDatasetTrainOnlyHint: "训练集已就绪；验证集和测试集缺失，不阻塞试跑，正式训练前建议补齐验证集。",
    trainingDatasetMissingValHint: "训练集已就绪；验证集缺失，正式训练前建议从训练集抽取或手动补充。",
    trainingDatasetMissingTestHint: "训练集和验证集已就绪；测试集缺失不阻塞训练。",
    trainingDatasetAllSplitsReadyHint: "训练集、验证集和测试集均已就绪。",
    issue: "问题",
    action: "操作",
    line: "第 {line} 行",
    instruction: "指令",
    input: "输入",
    result: "结果",
    yes: "是",
    no: "否",
    path: "路径",
    size: "大小",
    updated: "更新时间",
    adapter: "Adapter",
    baseModel: "基础模型",
    exists: "存在",
    prompt: "提示词",
    maxNewTokens: "最大生成 token",
    temperature: "Temperature",
    topP: "Top p",
    environmentCheck: "环境检查",
    modelManagement: "模型管理",
    modelManagementHint: "管理本地基础模型目录。只有可用于当前微调入口的模型会进入训练选择列表。",
    modelDirectories: "模型目录",
    modelDirectoriesHint: "添加一个或多个本地目录后，系统会递归扫描其中的可训练基础模型目录。",
    trainableModelDirs: "可训练基础模型目录",
    registeredModelsHint: "这些模型会出现在训练执行页的基础模型下拉框中。",
    scanResultsHint: "扫描完成后，可用模型可以加入基础模型列表；不可用文件只作为提示展示。",
    projectAndServices: "工程与服务",
    projectAndServicesHint: "这些信息来自当前工程及其启动配置，不代表训练任务参数。",
    systemDependencies: "系统依赖",
    systemDependenciesHint: "展示当前运行环境中的关键工具和训练依赖；依赖安装与升级由启动脚本统一处理。",
    trainingSupportScope: "训练支持范围",
    trainingSupportScopeHint: "这里优先说明哪些系统和硬件组合已经验证、计划支持或暂无计划支持微调。管理台能打开不等于可以训练。",
    trainingSupportCurrentHint: "当前版本的正式训练路线是 NVIDIA CUDA + bnb4/NF4 QLoRA。",
    trainingEnvironmentStatus: "当前训练环境",
    trainingEnvironmentStatusHint: "这里只展示本机环境与当前版本是否可训练；完整支持范围请查看 README。",
    currentEnvironmentSupported: "当前环境支持微调",
    currentEnvironmentNotSupported: "当前环境暂不支持微调",
    currentEnvironmentNeedsCheck: "当前环境需要处理",
    currentEnvironmentChecking: "正在检测本机环境",
    currentEnvironmentCheckingDetail: "正在读取操作系统、加速设备和训练依赖状态，请稍候。",
    currentEnvironmentVerifiedDetail: "本机属于当前版本已验证组合：Windows + NVIDIA CUDA。继续添加基础模型和语料后即可启动试运行训练。",
    currentEnvironmentCudaUnverifiedDetail: "检测到 NVIDIA CUDA，但当前系统组合尚未完成项目级验证。可继续使用管理台，正式训练前请先跑试运行训练。",
    currentEnvironmentUnsupportedDetail: "当前训练入口仅支持 NVIDIA CUDA + bnb4/NF4 QLoRA。此机器可以使用管理台，但暂不能启动微调。",
    currentEnvironmentMissingDetail: "检测到 CUDA 后端，但训练依赖尚未全部就绪。请重新运行启动脚本或在系统依赖区查看缺失项。",
    detectedOs: "操作系统",
    detectedAccelerator: "加速设备",
    detectedBackend: "训练后端",
    dependencyReadiness: "依赖状态",
    supportGroupVerified: "已验证可微调",
    supportGroupVerifiedSummary: "项目真实跑通过，推荐新用户优先使用。",
    supportGroupTarget: "计划支持微调",
    supportGroupTargetSummary: "技术路线明确，但还没有完成项目级验证。",
    supportGroupNoPlan: "暂无计划支持微调",
    supportGroupNoPlanSummary: "当前没有训练后端和验证路线，只保留必要识别。",
    supportOsWindows: "Windows",
    supportOsLinux: "Linux",
    supportOsMac: "macOS",
    supportOsWindowsLinux: "Windows / Linux",
    supportOsAny: "任意系统",
    supportHardwareNvidiaCuda: "NVIDIA GPU + CUDA",
    supportHardwareAppleMps: "Apple Silicon / MPS",
    supportHardwareIntelXpu: "Intel XPU",
    supportHardwareAmdRocm: "AMD GPU / ROCm",
    supportHardwareCpu: "仅 CPU",
    supportTrainingVerified: "已验证可训练",
    supportTrainingTarget: "目标支持，待更多验证",
    supportTrainingUnsupported: "暂无计划支持微调",
    supportNoteWindowsNvidia: "已在 Windows + RTX 5090 Laptop GPU + CUDA 13.0 上跑通 27B 试运行训练。",
    supportNoteLinuxNvidia: "设计目标是支持 CUDA 12+ 和足够显存的 NVIDIA Linux 环境，但当前项目尚未完成独立验证。",
    supportNoteMacApple: "计划以独立 MLX LoRA 后端支持 Apple Silicon，不复用当前 bitsandbytes QLoRA 路线。",
    supportNoteManagementOnly: "可使用管理台、语料管理和模型扫描；当前 QLoRA 训练入口不可用。",
    supportNoteNoTrainingBackend: "当前没有 ROCm/CPU 训练实现和验证路径。",
    currentMachine: "当前机器",
    notDetected: "未检测到",
    availableDependencies: "可用依赖",
    checkAgain: "重新检查",
    checkingDependencies: "正在检查依赖",
    requiredDependency: "核心依赖",
    optionalDependency: "可选能力",
    dependencyGroupRuntime: "基础运行时",
    dependencyGroupTraining: "训练框架",
    dependencyGroupCompute: "计算后端",
    dependencyGroupFrontend: "管理台构建",
    dependencyGroupOptional: "可选扩展",
    dependencyGroupOther: "其他依赖",
    dependencyReady: "可用",
    dependencyMissing: "缺失",
    dependencyIncompatible: "版本不满足",
    dependencyOptional: "未安装（可选）",
    repairAutoDependencies: "修复可自动处理项",
    dependencyRepairScope: "修复范围",
    dependencyRepairScopeHint: "LocalTune 只处理项目级依赖：项目内 Node/npm、前端依赖、CUDA 版 PyTorch 和 bitsandbytes。显卡驱动、操作系统组件、非 NVIDIA 后端需要用户按提示手动处理。",
    dependencyRepairResult: "修复输出",
    dependencyRepairNoOutput: "没有额外输出。",
    dependencyColumnName: "依赖",
    dependencyColumnVersion: "当前版本",
    dependencyColumnRequirement: "要求",
    dependencyColumnStatus: "状态",
    dependencyColumnRepair: "处理方式",
    dependencyRepairAuto: "可自动修复",
    dependencyRepairLauncher: "启动时处理",
    dependencyRepairManual: "手动配置",
    dependencyRepairUnknown: "待确认",
    repairByLauncher: "随启动脚本安装或升级。",
    repairTorchCuda: "可安装 CUDA 版 PyTorch；若安装后仍不可用，请检查 NVIDIA 驱动。",
    repairBitsAndBytesCuda: "可安装 bitsandbytes，用于 NVIDIA CUDA QLoRA。",
    repairUnsupportedBackend: "当前后端暂不支持自动配置此训练依赖。",
    repairPythonManual: "Python 由项目启动脚本创建；如果版本不对，请重新运行启动脚本。",
    repairComputeManual: "计算后端来自硬件和驱动，LocalTune 只检测，不安装系统驱动。",
    repairCudaManual: "CUDA 可用性由 PyTorch 与 NVIDIA 驱动决定；必要时请更新驱动后重启。",
    repairDriverManual: "NVIDIA 驱动需要手动安装或升级。",
    repairOptionalManual: "可选扩展不会自动安装，需要时按文档安装。",
    repairUnknownHint: "暂无明确修复策略。",
    localModelDir: "本地模型目录",
    modelDirs: "模型目录",
    addModelDir: "添加目录",
    chooseAndAddModelDir: "选择目录并扫描",
    chooseModelDirHint: "请选择本地基础模型所在的上级目录，系统会递归扫描可用模型。",
    modelDirAddedAndScanned: "目录已添加，发现 {count} 个可用模型",
    remove: "移除",
    scanModels: "扫描模型",
    scanAllModelDirs: "扫描全部目录",
    allModelDirs: "全部模型目录",
    registeredModels: "基础模型列表",
    registerModel: "加入模型列表",
    registered: "已在模型列表",
    removeModelTitle: "移除基础模型",
    removeModelConfirm: "从模型列表移除“{name}”？这不会删除磁盘上的模型文件。",
    active: "当前",
    loadMethods: "加载方式",
    loadMethod: "加载方式",
    modelLoadMethodsHint: "同一个基础模型可以配置多种加载方式；训练时选择其中一种。",
    modelFit_recommended: "适合当前硬件",
    modelFit_caution: "谨慎使用",
    modelFit_not_recommended: "不建议当前硬件",
    modelFit_unknown: "模型规模未知",
    modelFit_not_supported: "当前后端不支持",
    modelFitDetail_recommended: "{params} 预计需要约 {estimated} 显存，当前 {available} 显存有余量。",
    modelFitDetail_caution: "{params} 预计需要约 {estimated} 显存，已经接近当前 {available} 显存上限，建议先跑试运行训练。",
    modelFitDetail_not_recommended: "{params} 预计需要约 {estimated} 显存，可能超过当前 {available} 显存，不建议作为首次训练模型。",
    modelFitDetail_unknown: "无法从目录名或 config 识别参数规模；建议确认模型名称是否包含 7B、14B、27B 等信息。",
    modelFitDetail_not_supported: "当前训练入口需要 NVIDIA CUDA；此机器暂不能启动微调。",
    loadMethodAvailable: "可用",
    loadMethodMissing: "路径缺失",
    scanResults: "扫描结果",
    noModelsFound: "没有发现可用模型目录",
    noModelDirs: "暂无模型目录",
    noRegisteredModels: "暂无基础模型",
    modelNoUsableBranch: "暂无加载方式",
    modelsUnit: "个模型",
    foldersUnit: "个目录",
    filesUnit: "个文件",
    scanDirsUnit: "个扫描目录",
    weightFiles: "权重文件",
    ggufDetectedTitle: "发现不可用于微调的文件",
    ggufDetectedHint: "发现 {count} 个文件。当前微调入口不会把这些文件加入基础模型列表。",
    usableModelGuideTitle: "什么样的模型可以用于微调？",
    usableModelGuideHint: "请选择 Transformers 兼容的基础模型目录。它通常是一个文件夹，不是单个文件，并包含模型配置、分词器文件和权重文件。",
    usableModelGuideConfig: "包含 config.json，用于描述模型结构。",
    usableModelGuideTokenizer: "包含 tokenizer.json、tokenizer.model、tokenizer_config.json 或类似分词器文件。",
    usableModelGuideWeights: "包含 safetensors 或 .bin 权重文件，权重可能会拆成多个分片。",
    unsupportedModelGuideHint: "如果扫描到的是单个推理部署文件，当前微调入口不会把它加入基础模型列表。请下载或选择原始 Transformers 目录模型。",
    projectRoot: "项目根目录",
    configFile: "配置文件",
    projectVersion: "项目版本",
    dashboardDefaultPort: "管理台默认端口",
    activeBranch: "当前分支",
    activeProfile: "训练语料集",
    taskType: "任务类型",
    datasetFormat: "语料格式",
    dashboardPort: "管理台端口",
    runDoctor: "运行环境检查",
    doctorHint: "点击运行环境检查，检查 Python、计算后端、依赖和模型配置。",
    ok: "正常",
    missing: "缺失",
    instructionType: "指令语料",
    rewriteType: "改写语料",
    chatType: "对话语料",
    dpoType: "偏好语料",
    localTuneCorpusFormat: "LocalTune 语料格式",
    corpusFormatGuideHint: "统一使用 JSONL，每行一个训练样本。选择类型可查看对应结构和完整示例。",
    instructionCorpusHint: "适合通用问答、指令遵循和知识型任务。",
    rewriteCorpusHint: "适合改写、润色和风格迁移任务。",
    chatCorpusHint: "适合多轮对话、角色设定和对话风格保持。",
    dpoCorpusHint: "适合偏好优化，不直接用于当前 QLoRA SFT 流程。",
    corpusExample: "示例",
    copyExample: "复制示例",
    copyJsonlLine: "复制为 JSONL 行",
    jsonlCopyHint: "示例为方便阅读会分行展示；复制时会输出一行 JSON，可直接放入 JSONL 文件。",
    taskCenterHint: "集中查看训练任务。选择任务后可追踪参数、日志、产物和运行状态。",
    taskCenter: "任务中心",
    allTasks: "全部任务",
    trainingTasks: "训练任务",
    inferenceTasks: "推理任务",
    taskDetail: "任务详情",
    taskList: "任务列表",
    searchTasks: "搜索任务 ID、模型、语料或日志",
    allStatuses: "全部状态",
    newestFirst: "最新优先",
    oldestFirst: "最早优先",
    filteredTasks: "个结果",
    taskContext: "任务详情",
    taskSummary: "任务摘要",
    taskLogPreview: "任务日志预览",
    openTaskContext: "查看任务详情",
    taskParams: "任务参数",
    relatedArtifacts: "相关产物",
    noTaskSelected: "选择左侧任务查看详情",
    legacyTaskHint: "这是旧日志任务，缺少结构化任务元数据。",
    runKind: "任务类型",
    elapsed: "耗时",
    returnCode: "退出码",
    command: "命令",
    outputDir: "输出目录",
    params: "参数",
    logFile: "日志文件",
    finalAdapter: "最终 LoRA Adapter",
    checkpoint: "Checkpoint",
    mergedModel: "完整模型",
    metricsRun: "训练指标",
    copyId: "复制 ID",
    allArtifacts: "全部产物",
    deployableAdapters: "LoRA Adapter",
    trainingCheckpoints: "Checkpoint",
    mergedModels: "完整模型",
    metricsArtifacts: "训练指标",
    artifactList: "产物列表",
    artifactLibrary: "产物库",
    selectArtifact: "选择产物",
    searchArtifacts: "搜索产物名称、路径或任务 ID",
    allBranches: "全部加载方式",
    archivedArtifacts: "归档产物",
    archiveArtifact: "归档",
    restoreArtifact: "恢复",
    markBest: "标记最佳",
    unmarkBest: "取消最佳",
    bestArtifact: "最佳版本",
    archived: "已归档",
    validateArtifact: "推理验证",
    deleteArtifactTitle: "删除训练产物",
    deleteArtifactConfirm: "确定永久删除产物“{name}”吗？该操作会删除磁盘上的产物目录，无法撤销。",
    artifactUsability: "Adapter 文件检查",
    adapterBaseModel: "Adapter 基础模型",
    close: "关闭",
    collapseList: "收起列表",
    expandList: "展开列表",
    copyPath: "复制路径",
    copyInferenceArgs: "复制推理参数",
    finalAdapterHint: "可用于推理验证或合并的最终 LoRA Adapter。",
    checkpointHint: "训练过程中的阶段性保存点，可用于恢复或对比。",
    mergedModelHint: "Adapter 已与基础模型合并后的完整模型目录，可由兼容的 Transformers 推理工具直接加载。",
    mergePublish: "导出完整模型",
    mergePublishHint: "将当前 LoRA Adapter 合并回原始基础模型，生成可独立加载的完整 Transformers 模型目录。",
    mergeBaseModel: "原始基础模型",
    mergeOutputDir: "输出目录",
    mergeDtype: "合并精度",
    autoResolveBaseModel: "自动从训练记录或当前模型配置解析",
    autoOutputDir: "留空则输出到 outputs/localtune/merged",
    trustRemoteCode: "允许加载模型自定义代码",
    startMergePublish: "合并导出",
    startedAt: "开始时间",
    finishedAt: "结束时间",
    metricsRunHint: "LocalTune 指标文件，用于查看 loss、学习率等训练曲线。",
    artifactHint: "本地训练产物。",
    canRunInference: "推理就绪",
    sourceReliability: "来源记录",
    relatedTrainingTask: "关联训练任务",
    artifactTrainingSource: "训练来源",
    noSourceRecordDetail: "这个产物没有记录由哪次训练生成。",
    trainingContext: "训练上下文",
    weakRelationHint: "未记录来源。",
    exactRelationHint: "这个产物记录了对应的训练来源。",
    runId: "运行 ID",
    runMode: "运行模式",
    runStatus: "运行状态",
    runFinishedAt: "完成时间",
    datasetProfile: "训练语料集",
    runtimeConfig: "运行配置",
    inferredRelation: "未记录来源",
    exactRelation: "来源已记录",
    trainingParamSummary: "训练参数摘要",
    metricsSummary: "指标摘要",
    logPreview: "日志摘要",
    viewHere: "在此查看",
    config: "配置",
    trainData: "训练集",
    valData: "验证集",
    testData: "测试集",
    learningRate: "学习率",
    batchSize: "批大小",
    epochs: "训练轮数",
    estimatedVram: "预估显存",
    loraAlpha: "LoRA alpha",
    noManifest: "未记录由哪次训练生成",
    hasManifest: "已记录训练来源",
    status_unknown: "未知",
    status_running: "运行中",
    status_stopping: "停止中",
    status_idle: "空闲",
    status_completed: "已完成",
    status_failed: "失败",
    status_cancelled: "已取消",
    status_stopped: "已停止",
  },
  en: {
    app: "LocalTune Console",
    sub: "Local fine-tuning control center",
    workspace: "Workbench",
    overview: "Overview",
    overviewHint: "Review current training, datasets, models, artifacts, and items that need attention.",
    corpus: "Datasets",
    models: "Models",
    training: "Training",
    artifacts: "Artifacts",
    artifactsHint: "Manage final LoRA adapters and checkpoints with their exact training source.",
    inference: "Inference",
    history: "Task Center",
    environment: "Environment",
    refresh: "Refresh",
    open: "Open",
    openFolder: "Open Folder",
    status: "Task Status",
    monitor: "Run Monitor",
    existingCorpus: "Existing",
    createCorpus: "Derive",
    deriveTrainableCorpus: "Derive Training Corpus",
    formatGuide: "Guide",
    corpusHint: "Manage training datasets, raw materials, and sample checks. Training runs reference prepared training datasets from here.",
    deriveHint: "Create a new file only by copying, slicing, or sampling structured trainable JSONL datasets for short test runs and dataset cuts.",
    trainingHint: "Confirm the base model, load method, Training Dataset, and key training parameters before launching. The monitor refreshes logs, loss, and resources.",
    needSelectModel: "Select a base model",
    needValidModelPath: "Model path is unavailable",
    needSelectDataset: "Select a Training Dataset",
    needValidDataset: "Training Dataset validation failed",
    needOutputDir: "Output directory is missing",
    trainingAlreadyRunning: "A training run is already active",
    error_TRAINING_ALREADY_RUNNING: "A training run is already active. Open Training Execution to inspect it, then wait for completion or stop it before starting another run.",
    error_BASE_MODEL_REQUIRED: "No base model is selected. Add and scan a local model directory in Model Management, then select a trainable model in Training Execution.",
    error_DATASET_PROFILE_REQUIRED: "No Training Dataset is selected. Create or select a JSONL Training Dataset with a Training Set in Dataset Management.",
    error_CHECKPOINT_INVALID: "The selected checkpoint is unavailable. Pick an existing checkpoint directory from Training Artifacts, or disable resume.",
    error_BRANCH_BACKEND_UNSUPPORTED: "The selected load method does not support this compute backend. The verified public fine-tuning path requires NVIDIA CUDA + bnb4/NF4 QLoRA.",
    error_BRANCH_UNSUPPORTED: "The selected load method is not a supported LocalTune fine-tuning path. Use bnb4/NF4 QLoRA; NVFP4 is not a fine-tuning entry point in this release.",
    error_MODEL_DIRECTORY_UNRECOGNIZED: "This is not a trainable base model directory. Choose a Transformers model directory with config, tokenizer, and safetensors/bin weights; GGUF cannot be used as fine-tuning input.",
    error_MODEL_BRANCH_UNSUPPORTED: "No compatible fine-tuning load method is configured for this model format. Confirm the model is Transformers-compatible, review the model format in Model Management, and check training support in System Environment.",
    error_MODEL_NOT_FOUND: "That model is no longer in the list. Refresh the page and try again.",
    error_OUTPUT_DIR_REQUIRED: "Training output directory is not configured. Set training.output_dir in the config file, or regenerate the local config.",
    error_VALIDATION_ERROR: "The submitted data is invalid. Check the nearby field hint; if it is a path, confirm the directory exists and has the expected format.",
    error_TRAINING_START_FAILED: "Training did not start. Check Quick Start status first, then inspect System Environment, model path, Training Dataset, and task logs.",
    error_REQUEST_FAILED: "The operation failed. Try again.",
    trainingLaunch: "Launch Training",
    basicSetup: "Basic Setup",
    trainingScale: "Training Scale",
    loraAndSaving: "LoRA and Saving",
    safetyOptions: "Load Strategy",
    selectModel: "Select Model",
    modelPath: "Model Path",
    modelPathMissing: "Model path missing",
    trainingMonitoring: "Training Monitor",
    trainingMonitoringHint: "After launch, monitor task status, loss curves, resources, and logs here.",
    trainingTrace: "Training Context",
    noTrainingTrace: "Waiting for a training run",
    waitingForTrainingTask: "Waiting for a training run",
    trainingTraceEmptyHint: "After training starts, this panel shows the model, dataset, runtime config, and output location used by the current run.",
    trainingTraceShowsConfig: "Base model, load method, Training Dataset, and runtime config",
    trainingTraceShowsOutputs: "Output directory and artifacts recorded for this run",
    noActiveTrainingTask: "No active training task",
    startTrainingToMonitor: "Start training to show the current task status and key fields here.",
    noActiveTrainingLogs: "No training run is active, so historical task logs are not shown here.",
    recordedArtifacts: "Recorded Artifacts",
    noRecordedArtifactsYet: "No artifacts have been recorded for this training run yet. Final adapter and checkpoints are attached after completion.",
    postTrainingActions: "Post-run Actions",
    postTrainingActionsHint: "Continue from this run to inspect artifacts, validate output, or rerun with the same parameters.",
    viewArtifacts: "View Run Artifacts",
    validateFinalAdapter: "Validate Final LoRA Adapter",
    rerunTask: "Rerun with Same Params",
    noRerunParams: "No reusable params",
    exportRecipe: "Export Recipe",
    openRecipe: "Open Recipe",
    selectRecipe: "Select Training Recipe",
    applyRecipe: "Apply Recipe",
    envHint: "View project location, service settings, and local dependency health.",
    modelsHint: "Manage local base model directories and add usable models to training selectors after scanning.",
    goldenRun: "Quick Start",
    goldenRunNav: "Quick Start",
    goldenRunHint: "Fine-tuning a large model can be simple. We guide you through the first run.",
    quickStartSidebarHint: "Complete the first local fine-tune",
    quickStartPending: "{count} pending",
    quickStartNext: "Next: {step}",
    quickStartDone: "Test run complete",
    continueQuickStart: "Continue Quick Start",
    quickStartOverviewTitle: "Finish the first test run with the recommended flow",
    quickStartOverviewHint: "Prepare environment, base model, dataset, and a short test run before moving into the daily workspace.",
    viewQuickStart: "View Quick Start",
    goldenLoading: "Loading Quick Start...",
    goldenStartSmoke: "Start Test Run",
    goldenFixNextStep: "Fix Next Step",
    goldenPathTitle: "First Fine-tune Path",
    goldenPathHint: "Complete conditions in this order; the current item to handle is highlighted.",
    goldenStartupChecklist: "Pre-run Checklist",
    goldenStartupChecklistHint: "Training stays disabled until every required condition is ready.",
    goldenChecklistItem: "Item",
    goldenChecklistStatus: "Status",
    goldenChecklistDetail: "Details",
    goldenChecklistAction: "Action",
    goldenTestRunConfig: "Test Run Configuration",
    goldenTestRunConfigHint: "When requirements are ready, training starts with this configuration.",
    goldenAfterFixTitle: "What happens after setup",
    goldenAfterFixStep1: "Quick Start refreshes the check result.",
    goldenAfterFixStep2: "The start button becomes available and runs a short training job.",
    goldenAfterFixStep3: "Logs, loss, and artifacts appear in their management pages.",
    goldenMissingBaseModelShort: "Not selected",
    goldenReadinessScore: "Quick Start readiness score",
    goldenReadiness: "readiness",
    goldenNext: "Next",
    goldenRecommendedAction: "Recommended next action",
    goldenSelectStepHint: "Select a step in the journey.",
    goldenStatus_done: "Complete",
    goldenStatus_ready: "Ready",
    goldenStatus_blocked: "Needs setup",
    goldenStep_golden: "Quick Start",
    goldenStep_environment: "Environment Check",
    goldenStep_model: "Base Model",
    goldenStep_dataset: "Training Dataset",
    goldenStep_smoke: "Test Run",
    goldenStep_train: "Formal Training",
    goldenStep_evaluate: "Evaluation",
    goldenStepDetail_environment_done: "Core dependencies, accelerator backend, and runtime checks are ready for the first run.",
    goldenStepDetail_environment_blocked: "Check Python, compute backend, and core dependencies in System Environment.",
    goldenStepDetail_environment_ready: "Environment checks can be reviewed.",
    goldenStepDetail_model_done: "A usable base model is available.",
    goldenStepDetail_model_blocked: "Add a local model directory, scan it, and add the detected model to the model list.",
    goldenStepDetail_model_ready: "Select the base model for this run.",
    goldenStepDetail_dataset_done: "A validated Training Dataset is available.",
    goldenStepDetail_dataset_blocked: "Import JSONL training data, create a Training Dataset, and pass format checks.",
    goldenStepDetail_dataset_ready: "Select a Training Dataset for the first run.",
    goldenStepDetail_smoke_done: "The latest test run completed.",
    goldenStepDetail_smoke_ready: "Review test-run parameters and run one training step to prove model loading, data reading, loss logging, and artifact wiring.",
    goldenStepDetail_smoke_blocked: "Prepare environment, model, and dataset first.",
    goldenStepDetail_train_done: "An Adapter is available for validation.",
    goldenStepDetail_train_ready: "The test run passed. Promote the recipe to a formal training run.",
    goldenStepDetail_train_blocked: "Complete a test run before formal training.",
    goldenStepDetail_evaluate_done: "An evaluation record is available.",
    goldenStepDetail_evaluate_ready: "Compare Base vs Adapter and save a report.",
    goldenStepDetail_evaluate_blocked: "Evaluate after training completes and an Adapter is produced.",
    goldenAction_golden: "Review readiness",
    goldenAction_environment: "Fix environment",
    goldenAction_model: "Add or select a base model",
    goldenAction_dataset: "Import training corpus",
    goldenAction_smoke: "Start test run",
    goldenAction_train: "Start formal training",
    goldenStartFormal: "Start Formal Training",
    goldenAction_evaluate: "Validate Adapter output",
    goldenBlockers: "To do before training",
    goldenBlocker_environment: "Environment is not ready: check required dependencies, accelerator backend, and runtime setup.",
    goldenBlocker_model: "No usable local base model is available. Add and scan a model directory in Model Management.",
    goldenBlocker_dataset: "No validated Training Dataset is available. Import JSONL training data first.",
    goldenSuccessMetrics: "First Run Checklist",
    goldenSuccessMetricsHint: "Check whether this flow has the key results needed for training, monitoring, and validation.",
    goldenMetricTime: "Time to evaluated Adapter",
    goldenMetricTimeHint: "tracked after first completion",
    goldenMetricSmoke: "Test run success",
    goldenMetricSmokeHint: "model load, data read, and loss",
    goldenMetricData: "Data quality",
    goldenMetricDataHint: "validated Training Dataset",
    goldenMetricEvaluation: "Evaluation readiness",
    goldenMetricEvaluationHint: "Base vs Adapter report",
    goldenMetricValuePending: "Pending",
    goldenMetricValueReady: "Ready",
    goldenMetricValueWaitingAdapter: "Waiting for Adapter",
    goldenMetricValueNotMeasured: "Not measured yet",
    goldenRunCapsule: "Run Capsule",
    goldenRunCapsuleHint: "Portable first-run context",
    goldenWaitingForTraining: "Waiting for training",
    goldenSmokeRecipe: "Test Run Recipe",
    goldenSmokeRecipeHint: "Safe default for the first proof run",
    goldenRunSmoke: "Run Test",
    goldenPromote: "Promote",
    goldenLastChecked: "Last checked",
    goldenLocalOnly: "Local-only status. No datasets, models, or training outputs are uploaded by this page.",
    goldenTrainabilityLabel: "Current Status",
    goldenModelGuidanceLabel: "Model selection guidance",
    goldenModelGuidanceTitle_ready: "Start with a base model that leaves VRAM headroom",
    goldenModelGuidanceTitle_unknown: "Model size guidance is not available yet",
    goldenModelGuidanceTitle_not_supported: "This hardware cannot use the fine-tuning entry yet",
    goldenModelGuidance_ready: "Current {device} has about {vram} VRAM. Prefer bnb4/NF4 QLoRA models up to {recommended}; around {caution}, run a test run first.",
    goldenModelGuidance_unknown: "The console cannot read available VRAM yet. After adding a model, it will still try to infer size from the directory name and config.",
    goldenModelGuidance_not_supported: "The current fine-tuning path requires NVIDIA CUDA. You can still manage datasets and models, but should not expect a local fine-tuning result on this machine.",
    goldenModelGuidanceAction: "Manage base models",
    recommendedModelsLabel: "Recommended for the current device",
    recommendedModelsTitle: "Recommended Models",
    recommendedModelsHint: "Detected {device} with about {vram} VRAM.",
    loadingModelRecommendations: "Preparing model recommendations...",
    recommendedMinVram: "Suggested VRAM",
    recommendedProvider: "Source",
    recommendedModelFit_recommended: "Recommended",
    recommendedModelFit_caution: "Try first",
    recommendedModelFit_too_large: "Not advised",
    recommendedModelFit_unknown: "Check first",
    recommendedModelFit_unsupported: "Not trainable",
    openDownloadPage: "Open Page",
    copyDownloadCommand: "Copy Command",
    startDownload: "Start Download",
    cancelDownload: "Cancel",
    copied: "Copied",
    downloadDependencyMissing: "Download dependency missing",
    downloadDependencyMissingHint: "Copy the command, or rerun the launcher to install optional dependencies.",
    downloadStatus_running: "Downloading",
    downloadStatus_stopping: "Stopping",
    downloadStatus_completed: "Completed",
    downloadStatus_missing: "Files removed",
    downloadStatus_failed: "Failed",
    downloadStatus_cancelled: "Cancelled",
    goldenReadiness_ready_title: "This machine can start a test run",
    goldenReadiness_ready_detail: "Environment, base model, and training dataset are ready. Start with a 1-step test run to confirm model loading, data reading, loss logging, and artifact wiring.",
    goldenReadiness_ready_action: "Start test run",
    goldenReadiness_running_title: "Training is already running",
    goldenReadiness_running_detail: "A training task is active. Open Training Execution to monitor logs, loss, and resource usage, then wait for completion or stop it before starting another task.",
    goldenReadiness_running_action: "View training",
    goldenReadiness_unsupported_backend_title: "This hardware cannot fine-tune yet",
    goldenReadiness_unsupported_backend_detail: "The verified fine-tuning path in this public release requires NVIDIA CUDA. Non-CUDA machines can inspect the project and datasets, but should not expect a fine-tuned result yet.",
    goldenReadiness_unsupported_backend_action: "View environment",
    goldenReadiness_missing_environment_title: "Environment is not ready for training",
    goldenReadiness_missing_environment_detail: "Check Python, CUDA, PyTorch, bitsandbytes, and the frontend toolchain first. System Environment shows missing items and the current compute backend.",
    goldenReadiness_missing_environment_action: "View environment",
    goldenReadiness_missing_model_title: "No trainable base model yet",
    goldenReadiness_missing_model_detail: "Add and scan a local model directory in Model Management. The current training entry requires a Transformers-compatible base model directory; GGUF cannot be used as fine-tuning input.",
    goldenReadiness_missing_model_action: "Add base model",
    goldenReadiness_missing_dataset_title: "No usable training dataset yet",
    goldenReadiness_missing_dataset_detail: "Import or select JSONL training data and create a Training Dataset with a Training Set. Training can start after format validation passes.",
    goldenReadiness_missing_dataset_action: "Prepare dataset",
    noData: "No data",
    noArtifactsYet: "After a test run or full training run, LoRA Adapters, Checkpoints, or merged models will appear here.",
    noMatchingDatasetProfiles: "No matching training dataset",
    noMatchingMaterials: "No matching source material",
    start: "Start Training",
    stop: "Stop",
    runInference: "Run Inference",
    selectAdapter: "Select Adapter",
    needSelectAdapter: "Select an adapter to validate",
    inferenceHint: "Run a real inference check with the final adapter.",
    inferenceSetup: "Validation Setup",
    singleInference: "Single",
    baseAdapterCompare: "Base / Adapter",
    batchValidation: "Batch Validation",
    datasetSplit: "Dataset Split",
    sampleCount: "Samples",
    systemPrompt: "System Prompt",
    maxInputTokens: "Max Input Tokens",
    stopWords: "Stop Words",
    stopWordsHint: "Separate multiple stop words with commas",
    baseModelOutput: "Base Model Output",
    adapterOutput: "Adapter Output",
    expectedOutput: "Expected Output",
    evaluationReport: "Evaluation Report",
    runBatchValidation: "Run Batch Validation",
    openReport: "Open Report",
    jsonReport: "JSON Report",
    markdownReport: "Markdown Report",
    waitingInferenceOutput: "Waiting for inference output...",
    running: "Running",
    idle: "Idle",
    completed: "Completed",
    failed: "Failed",
    checking: "Checking",
    valid: "Valid",
    invalid: "Invalid",
    activeCorpus: "Active Corpus",
    corpusLibrary: "Corpus Library",
    selectCorpus: "Select Corpus",
    datasetFiles: "dataset files",
    rawMaterialsExcluded: "raw materials excluded",
    trainableCorpus: "Training Corpus",
    trainableCorpusFiles: "JSONL Files",
    readyTrainingDatasets: "Ready Training Datasets",
    trainingDatasetInventoryHint: "Training selects a Training Dataset; it counts as ready when the Training Set exists and validation passes.",
    trainingDatasetInventoryEmpty: "No Training Dataset yet. Prepare JSONL data in Corpus Management first.",
    trainingDatasets: "Training Datasets",
    trainingDatasetsHint: "A training dataset is the data unit referenced by training runs. Each dataset contains Training, Validation, and Test sets.",
    selectTrainingDataset: "Select Dataset",
    rawMaterials: "Raw Materials",
    rawMaterial: "Raw Material",
    materialFiles: "material files",
    selectMaterial: "Select Material",
    materialFile: "Material File",
    materialHint: "Raw materials are for reading, locating, and source tracking.",
    trainableCorpusHint: "{files} JSONL files can be referenced by Training Datasets. {profiles} Training Datasets are available for training, with {materials} raw materials managed separately.",
    datasetProfileInventory: "Training Dataset Inventory",
    datasetProfileAlignmentHint: "Training selects a Training Dataset; each Training Dataset references Training, Validation, and Test JSONL files.",
    materialInfo: "Material Info",
    materialProperties: "Material Properties",
    materialPropertiesHint: "Shown as file assets, not parsed as training sample structure.",
    materialPreview: "Material Preview",
    materialPreviewHint: "Shows readable text snippets for quick content inspection.",
    materialUsage: "Usage",
    materialUsageHint: "Use as a reference during manual corpus preparation.",
    sourcePreview: "Source Preview",
    contentPreview: "Content Preview",
    fileType: "File Type",
    datasetComposition: "Dataset Composition",
    datasetSplitGroupTitle: "Training / Validation / Test",
    datasetCompositionHint: "Training uses this Training, Validation, and Test file group.",
    selectDatasetProfileToInspect: "Select a training dataset to inspect its composition.",
    missingSplitHint: "This split is missing, so no samples are available.",
    splitFromTrain: "Extract Validation/Test from Train",
    splitFromTrainHint: "Creates new Training, Validation, and Test files and writes them back to the selected profile.",
    createMissingSplits: "Create Missing Splits",
    missingSplits: "Missing: {roles}",
    valRatio: "Validation Ratio",
    testRatio: "Test Ratio",
    seed: "Seed",
    trainDataRequired: "A usable training file is required.",
    previewSamples: "Preview Samples",
    ready: "Ready",
    notReady: "Not Ready",
    validation: "Validation",
    commonProperties: "Common Properties",
    corpusFile: "Corpus File",
    filePath: "File Path",
    folder: "Folder",
    sampleRows: "Sample Rows",
    trainable: "Trainable",
    formatCheck: "Format Check",
    samplePreview: "Sample Preview",
    loadingCorpusSamples: "Loading corpus samples...",
    searchSamples: "Search sample content",
    sampleRange: "{start}-{end} of {total}",
    previousPage: "Previous page",
    nextPage: "Next page",
    overwriteDerivedFileTitle: "Overwrite Derived File",
    overwriteDerivedFileConfirm: "The output file already exists. Overwrite it? This cannot be undone.",
    artifactCount: "Artifacts",
    latestLoss: "Latest Loss",
    currentTraining: "Current Training",
    latestTraining: "Latest Training",
    noTrainingHistory: "No training history yet",
    startTraining: "Start Training",
    enterTrainingPage: "Open Training",
    overviewNoActiveTraining: "No training task is running. Open the Training page to confirm the base model, Training Dataset, and parameters before launching a new run.",
    viewTraining: "View Training",
    viewTaskDetails: "View Task Details",
    taskLoss: "Training Loss",
    metricPoints: "metric points",
    fromFirstStep: "from the first recorded point",
    lossBelongsToTask: "Only data from this task is shown",
    firstValue: "First",
    latestValue: "Latest",
    attentionItems: "Attention Needed",
    attentionSummary: "{count} issue groups need attention",
    noAttentionItems: "Nothing needs attention",
    allProfilesReady: "All Training Datasets are ready",
    profilesNeedAttention: "Some Training Datasets need attention",
    noDatasetProfiles: "No Training Datasets yet",
    usableModels: "Usable Base Models",
    readyForInference: "Loadable with the base model for inference",
    noDeployableAdapters: "No LoRA adapters",
    invalidProfilesIssue: "{count} Training Datasets are unavailable",
    noDatasetProfilesIssue: "No ready Training Dataset yet",
    noUsableModelsIssue: "No usable base model",
    invalidAdaptersIssue: "{count} Adapters failed validation",
    failedTasksIssue: "{count} recent training tasks failed",
    unlinkedArtifactsIssue: "{count} legacy artifacts have no exact training source",
    sourceMissing: "Training source missing",
    recentTrainingTasks: "Recent Training Tasks",
    recentTrainingTasksHint: "Status, dataset, and outputs from the five latest runs",
    recentArtifacts: "Recent Training Outputs",
    recentArtifactsHint: "Recently generated Adapters and checkpoints",
    viewAll: "View All",
    systemResources: "System Resources",
    systemResourcesHint: "Current CPU, memory, and GPU state; refreshed while training runs",
    loss: "Loss",
    noLossData: "No loss data",
    singleLossHint: "A trend line needs at least two points",
    rowsUnit: "rows",
    samplesUnit: "samples",
    previewRowsUnit: "preview rows",
    cpu: "CPU",
    memory: "Memory",
    gpuMemory: "GPU Memory",
    gpuUtil: "GPU Util",
    gpuTemperature: "GPU Temperature",
    gpuTemperatureHint: "Reported by the hardware monitoring backend",
    gpuPower: "GPU Power",
    notAvailable: "Not available",
    taskLogs: "Task Logs",
    trainingStep: "Progress",
    trainingSpeed: "Speed",
    eta: "ETA",
    epoch: "Epoch",
    searchLogs: "Search logs",
    allLogs: "All",
    metricLogs: "Metrics",
    warningLogs: "Warnings",
    errorLogs: "Errors",
    followLogs: "Follow latest",
    jobId: "Job ID",
    mode: "Mode",
    trainingPlan: "Training Plan",
    trainingPlanHint: "Choose the training intent first. LocalTune applies matching dataset, step, logging, and save presets.",
    smokePlan: "Test Run Check",
    smokePlanHint: "Validates model loading, data reading, loss logging, and artifact wiring. Not for quality evaluation.",
    smokePlanPreset: "Fixed 20 steps · log every step · save at step 20",
    smokeDatasetPolicy: "Prefers a small training dataset",
    fullPlan: "Full Training",
    fullPlanHint: "Creates a LoRA Adapter for real use with the full training configuration.",
    fullPlanPreset: "Full dataset · steps controlled by configuration",
    fullDatasetPolicy: "Prefers the complete training dataset",
    branch: "Load Method",
    dataset: "Dataset",
    started: "Started",
    finished: "Finished",
    timeRange: "Run Time",
    log: "Log",
    smoke: "Test Run",
    full: "Full",
    formal: "Full",
    maxSteps: "Max Steps",
    maxSeqLength: "Max Seq Length",
    loraR: "LoRA r",
    gradAccumulation: "Grad Accumulation",
    loggingSteps: "Logging Steps",
    saveSteps: "Save Steps",
    resumeFromCheckpoint: "Training Start Point",
    startFromBaseModel: "New run: start from base model",
    continueFromCheckpoint: "Resume from checkpoint",
    disableFallbackChain: "Use only the selected load method",
    loadingStrategyHint: "When enabled, this run strictly uses the selected load method. If the environment does not match, it fails instead of switching to another method.",
    currentComputeBackend: "Current compute backend",
    supportedComputeBackends: "Supported backends",
    backendUnsupported: "The current compute backend is not supported by this load method",
    useConfig: "Leave blank for default",
    useDefaultValue: "Leave blank for default",
    source: "Source",
    sourceDataset: "Source Dataset",
    output: "Output",
    deriveMode: "Mode",
    limit: "Limit",
    head: "Head",
    tail: "Tail",
    sample: "Sample",
    copy: "Copy",
    generateFile: "Generate File",
    generateDerivedFile: "Generate Derived File",
    deriveBoundaryTitle: "Trainable datasets only",
    deriveBoundaryHint: "Raw materials are not read here. The source must already be a trainable JSONL file.",
    noTrainableCorpus: "No trainable corpus available",
    datasetProfiles: "Training Datasets",
    datasetProfilesHint: "Training starts from one selected training dataset. Review Training, Validation, and Test files, rows, and validation status here.",
    addTrainingDataset: "Add Training Dataset",
    importTrainingCorpus: "Create from Files",
    importTrainingCorpusDone: "Imported {name} and created a training dataset",
    createDatasetProfile: "New Empty Dataset",
    editDatasetProfile: "Edit Training Dataset",
    copyDatasetProfile: "Copy Training Dataset",
    deleteDatasetProfileTitle: "Delete Training Dataset",
    deleteDatasetProfileConfirm: "Delete training dataset “{name}”? The dataset files themselves will not be deleted.",
    datasetProfileEditorHint: "A training dataset groups training, validation, and test files. Deleting it does not delete the underlying files.",
    datasetProfileFileHint: "Training data is required. Validation and test data can be created later from the training split.",
    profileIdentity: "Dataset Information",
    profileId: "Dataset ID",
    name: "Name",
    description: "Description",
    edit: "Edit",
    delete: "Delete",
    confirmDelete: "Delete",
    confirmRemove: "Remove",
    confirmOverwrite: "Overwrite",
    save: "Save",
    cancel: "Cancel",
    notSelected: "Not selected",
    validationPassed: "Validation Passed",
    validationFailed: "Validation Failed",
    validationSummary: "{errors} errors, {warnings} warnings",
    revalidate: "Revalidate",
    selectedDatasetProfile: "Training Dataset for This Run",
    selectDatasetProfile: "Select a training dataset",
    currentTrainingDataset: "Training Dataset",
    searchDatasets: "Search training datasets",
    datasetStatus: "Status",
    readyToTrain: "Ready to Train",
    readyToTrainHint: "The Training Set is ready and validation passed; a missing Test Set does not block training.",
    readyForTrialRun: "Ready for Trial Run",
    notReadyToTrain: "Not Ready",
    notReadyToTrainHint: "Add a Training Set and pass format checks before training.",
    trainingDatasetMissingTrainHint: "Add a Training Set and pass format checks before training.",
    trainingDatasetValidationFailedHint: "The dataset did not pass format checks. Review and fix the issues first.",
    trainingDatasetTrainOnlyHint: "The Training Set is ready. Validation and Test sets are missing; this is fine for a trial run, but add Validation before full training.",
    trainingDatasetMissingValHint: "The Training Set is ready. Validation is missing; extract it from the Training Set or add it manually before full training.",
    trainingDatasetMissingTestHint: "Training and Validation sets are ready. A missing Test Set does not block training.",
    trainingDatasetAllSplitsReadyHint: "Training, Validation, and Test sets are ready.",
    issue: "Issue",
    action: "Action",
    line: "Line {line}",
    instruction: "Instruction",
    input: "Input",
    result: "Result",
    yes: "Yes",
    no: "No",
    path: "Path",
    size: "Size",
    updated: "Updated",
    adapter: "Adapter",
    baseModel: "Base Model",
    exists: "Exists",
    prompt: "Prompt",
    maxNewTokens: "Max New Tokens",
    temperature: "Temperature",
    topP: "Top p",
    environmentCheck: "Environment Check",
    modelManagement: "Model Management",
    modelManagementHint: "Manage local base model directories. Only models usable by the current fine-tuning entry appear in training selectors.",
    modelDirectories: "Model Directories",
    modelDirectoriesHint: "Add one or more local directories. LocalTune recursively scans them for trainable base model directories.",
    trainableModelDirs: "Trainable Base Model Directories",
    registeredModelsHint: "These models appear in the base model selector on the Training page.",
    scanResultsHint: "After scanning, usable models can be added to the base model list. Unsupported files are shown only as notices.",
    projectAndServices: "Project and Services",
    projectAndServicesHint: "These values come from the current project and startup configuration, not from training task parameters.",
    systemDependencies: "System Dependencies",
    systemDependenciesHint: "Shows key tools and training packages in the current environment. Installation and upgrades are handled by the startup script.",
    trainingSupportScope: "Training Support Scope",
    trainingSupportScopeHint: "This view prioritizes which OS and hardware combinations are verified, planned, or not planned for fine-tuning. Opening the console does not mean the machine can fine-tune.",
    trainingSupportCurrentHint: "The supported training path in this release is NVIDIA CUDA + bnb4/NF4 QLoRA.",
    trainingEnvironmentStatus: "Current Training Environment",
    trainingEnvironmentStatusHint: "This section only shows this machine and whether the current release can train on it. See README for the full support matrix.",
    currentEnvironmentSupported: "This environment can fine-tune",
    currentEnvironmentNotSupported: "This environment cannot fine-tune yet",
    currentEnvironmentNeedsCheck: "This environment needs attention",
    currentEnvironmentChecking: "Checking this machine",
    currentEnvironmentCheckingDetail: "Reading operating system, accelerator, and training dependency status.",
    currentEnvironmentVerifiedDetail: "This machine matches the verified combination for this release: Windows + NVIDIA CUDA. Add a base model and corpus, then run a test run.",
    currentEnvironmentCudaUnverifiedDetail: "NVIDIA CUDA was detected, but this OS combination has not completed project-level validation. Use the console normally and run a test run before formal training.",
    currentEnvironmentUnsupportedDetail: "The current training entry supports NVIDIA CUDA + bnb4/NF4 QLoRA only. This machine can use the console, but fine-tuning is disabled for now.",
    currentEnvironmentMissingDetail: "CUDA was detected, but some training dependencies are not ready. Restart with the launcher or check the dependency section below.",
    detectedOs: "Operating System",
    detectedAccelerator: "Accelerator",
    detectedBackend: "Training Backend",
    dependencyReadiness: "Dependency Status",
    supportGroupVerified: "Verified for fine-tuning",
    supportGroupVerifiedSummary: "The project has actually completed a run on this combination; recommended for new users.",
    supportGroupTarget: "Planned fine-tuning support",
    supportGroupTargetSummary: "The technical path is clear, but project-level validation is not complete yet.",
    supportGroupNoPlan: "No fine-tuning support planned",
    supportGroupNoPlanSummary: "No training backend or validation path is available in the current roadmap.",
    supportOsWindows: "Windows",
    supportOsLinux: "Linux",
    supportOsMac: "macOS",
    supportOsWindowsLinux: "Windows / Linux",
    supportOsAny: "Any OS",
    supportHardwareNvidiaCuda: "NVIDIA GPU + CUDA",
    supportHardwareAppleMps: "Apple Silicon / MPS",
    supportHardwareIntelXpu: "Intel XPU",
    supportHardwareAmdRocm: "AMD GPU / ROCm",
    supportHardwareCpu: "CPU only",
    supportTrainingVerified: "Verified for training",
    supportTrainingTarget: "Target support, needs more validation",
    supportTrainingUnsupported: "No fine-tuning support planned",
    supportNoteWindowsNvidia: "Verified on Windows + RTX 5090 Laptop GPU + CUDA 13.0 with a 27B test run.",
    supportNoteLinuxNvidia: "Designed to support NVIDIA Linux environments with CUDA 12+ and enough VRAM, but not independently validated in this project yet.",
    supportNoteMacApple: "Planned through a separate MLX LoRA backend for Apple Silicon, not by reusing the current bitsandbytes QLoRA path.",
    supportNoteManagementOnly: "Console, dataset management, and model scanning can be used; the current QLoRA training entry is unavailable.",
    supportNoteNoTrainingBackend: "No ROCm/CPU training implementation or validation path is available.",
    currentMachine: "Current machine",
    notDetected: "Not detected",
    availableDependencies: "Available Dependencies",
    checkAgain: "Check Again",
    checkingDependencies: "Checking dependencies",
    requiredDependency: "Core dependency",
    optionalDependency: "Optional capability",
    dependencyGroupRuntime: "Runtime",
    dependencyGroupTraining: "Training Stack",
    dependencyGroupCompute: "Compute Backend",
    dependencyGroupFrontend: "Console Build",
    dependencyGroupOptional: "Optional Extensions",
    dependencyGroupOther: "Other Dependencies",
    dependencyReady: "Available",
    dependencyMissing: "Missing",
    dependencyIncompatible: "Version mismatch",
    dependencyOptional: "Not installed (optional)",
    repairAutoDependencies: "Repair Auto-Fixable Items",
    dependencyRepairScope: "Repair Scope",
    dependencyRepairScopeHint: "LocalTune only handles project-level dependencies: project-local Node/npm, frontend packages, CUDA PyTorch, and bitsandbytes. GPU drivers, OS components, and non-NVIDIA backends require manual action.",
    dependencyRepairResult: "Repair Output",
    dependencyRepairNoOutput: "No additional output.",
    dependencyColumnName: "Dependency",
    dependencyColumnVersion: "Current",
    dependencyColumnRequirement: "Required",
    dependencyColumnStatus: "Status",
    dependencyColumnRepair: "Action",
    dependencyRepairAuto: "Auto repair",
    dependencyRepairLauncher: "Launcher setup",
    dependencyRepairManual: "Manual setup",
    dependencyRepairUnknown: "Unknown",
    repairByLauncher: "Installed or upgraded by the launcher.",
    repairTorchCuda: "Can install CUDA PyTorch. If CUDA is still unavailable afterward, check the NVIDIA driver.",
    repairBitsAndBytesCuda: "Can install bitsandbytes for NVIDIA CUDA QLoRA.",
    repairUnsupportedBackend: "This backend is not auto-configured for the current training dependency.",
    repairPythonManual: "Python is created by the project launcher. If the version is wrong, run the launcher again.",
    repairComputeManual: "Compute backend comes from hardware and drivers. LocalTune detects it but does not install system drivers.",
    repairCudaManual: "CUDA availability depends on PyTorch and the NVIDIA driver. Update the driver and restart if needed.",
    repairDriverManual: "NVIDIA driver installation or upgrades must be done manually.",
    repairOptionalManual: "Optional extensions are not installed automatically. Install them from the docs when needed.",
    repairUnknownHint: "No repair strategy is available yet.",
    localModelDir: "Local Model Directory",
    modelDirs: "Model Directories",
    addModelDir: "Add Directory",
    chooseAndAddModelDir: "Choose and Scan Directory",
    chooseModelDirHint: "Choose a parent directory that contains local base models. LocalTune will scan it recursively.",
    modelDirAddedAndScanned: "Directory added. Found {count} usable models.",
    remove: "Remove",
    scanModels: "Scan Models",
    scanAllModelDirs: "Scan All Directories",
    allModelDirs: "All Model Directories",
    registeredModels: "Base Model List",
    registerModel: "Add to Models",
    registered: "In Model List",
    removeModelTitle: "Remove Base Model",
    removeModelConfirm: "Remove “{name}” from the model list? This will not delete model files from disk.",
    active: "Active",
    loadMethods: "Load Methods",
    loadMethod: "Load Method",
    modelLoadMethodsHint: "One base model can define multiple loading methods. Pick one when starting training.",
    modelFit_recommended: "Fits this hardware",
    modelFit_caution: "Use with caution",
    modelFit_not_recommended: "Not recommended here",
    modelFit_unknown: "Model size unknown",
    modelFit_not_supported: "Backend unsupported",
    modelFitDetail_recommended: "{params} is estimated to need about {estimated} VRAM; current {available} VRAM has headroom.",
    modelFitDetail_caution: "{params} is estimated to need about {estimated} VRAM, close to the current {available} limit. Run a test run first.",
    modelFitDetail_not_recommended: "{params} is estimated to need about {estimated} VRAM and may exceed current {available} VRAM. Not recommended for a first run.",
    modelFitDetail_unknown: "Cannot infer parameter size from the directory name or config. Check whether the model name includes values such as 7B, 14B, or 27B.",
    modelFitDetail_not_supported: "The current fine-tuning entry requires NVIDIA CUDA; this machine cannot start local fine-tuning yet.",
    loadMethodAvailable: "Available",
    loadMethodMissing: "Path Missing",
    scanResults: "Scan Results",
    noModelsFound: "No usable model directories found",
    noModelDirs: "No model directories",
    noRegisteredModels: "No base models",
    modelNoUsableBranch: "No loading methods",
    modelsUnit: "models",
    foldersUnit: "folders",
    filesUnit: "files",
    scanDirsUnit: "scan dirs",
    weightFiles: "weight files",
    ggufDetectedTitle: "Unsupported files found",
    ggufDetectedHint: "Found {count} file(s). The current fine-tuning entry will not add these files to the base model list.",
    usableModelGuideTitle: "What counts as a trainable model?",
    usableModelGuideHint: "Choose a Transformers-compatible base model directory. It is usually a folder, not a single file, and contains model config, tokenizer files, and weights.",
    usableModelGuideConfig: "Includes config.json for the model architecture.",
    usableModelGuideTokenizer: "Includes tokenizer.json, tokenizer.model, tokenizer_config.json, or similar tokenizer files.",
    usableModelGuideWeights: "Includes safetensors or .bin weight files, sometimes split into multiple shards.",
    unsupportedModelGuideHint: "GGUF is usually an inference/deployment format. The current fine-tuning entry will not add it to the base model list. Download or select the original Transformers directory model instead.",
    projectRoot: "Project Root",
    configFile: "Config File",
    projectVersion: "Project Version",
    dashboardDefaultPort: "Default Dashboard Port",
    activeBranch: "Active Branch",
    activeProfile: "Training Dataset",
    taskType: "Task Type",
    datasetFormat: "Dataset Format",
    dashboardPort: "Dashboard Port",
    runDoctor: "Run Doctor",
    doctorHint: "Click Run Doctor to check Python, compute backend, dependencies, and model configuration.",
    ok: "OK",
    missing: "Missing",
    instructionType: "Instruction",
    rewriteType: "Rewrite",
    chatType: "Chat",
    dpoType: "DPO",
    localTuneCorpusFormat: "LocalTune Corpus Formats",
    corpusFormatGuideHint: "Use JSONL with one training sample per line. Select a type to view its structure and complete example.",
    instructionCorpusHint: "For general Q&A, instruction following, and knowledge tasks.",
    rewriteCorpusHint: "For rewriting, polishing, and style-transfer tasks.",
    chatCorpusHint: "For multi-turn conversations, roles, and conversational style.",
    dpoCorpusHint: "For preference optimization; not used directly by the current QLoRA SFT workflow.",
    corpusExample: "Example",
    copyExample: "Copy Example",
    copyJsonlLine: "Copy JSONL Line",
    jsonlCopyHint: "Examples are formatted for readability. Copy outputs one JSON object on a single line for JSONL files.",
    taskCenterHint: "Review training jobs in one place. Select a task to inspect parameters, logs, artifacts, and status.",
    taskCenter: "Task Center",
    allTasks: "All Tasks",
    trainingTasks: "Training",
    inferenceTasks: "Inference",
    taskDetail: "Task Detail",
    taskList: "Task List",
    searchTasks: "Search ID, model, dataset, or log",
    allStatuses: "All Statuses",
    newestFirst: "Newest First",
    oldestFirst: "Oldest First",
    filteredTasks: "results",
    taskContext: "Task Detail",
    taskSummary: "Task Summary",
    taskLogPreview: "Task Log Preview",
    openTaskContext: "View Task Detail",
    taskParams: "Task Params",
    relatedArtifacts: "Related Artifacts",
    noTaskSelected: "Select a task on the left",
    legacyTaskHint: "This is a legacy log task without structured metadata.",
    runKind: "Task Type",
    elapsed: "Elapsed",
    returnCode: "Return Code",
    command: "Command",
    outputDir: "Output Dir",
    params: "Params",
    logFile: "Log File",
    finalAdapter: "Final LoRA Adapter",
    checkpoint: "Checkpoint",
    mergedModel: "Full Model",
    metricsRun: "Training Metrics",
    copyId: "Copy ID",
    allArtifacts: "All Artifacts",
    deployableAdapters: "LoRA Adapters",
    trainingCheckpoints: "Checkpoints",
    mergedModels: "Full Models",
    metricsArtifacts: "Training Metrics",
    artifactList: "Artifact List",
    artifactLibrary: "Artifact Library",
    selectArtifact: "Select Artifact",
    searchArtifacts: "Search name, path, or task ID",
    allBranches: "All Load Methods",
    archivedArtifacts: "Archived",
    archiveArtifact: "Archive",
    restoreArtifact: "Restore",
    markBest: "Mark Best",
    unmarkBest: "Unmark Best",
    bestArtifact: "Best Version",
    archived: "Archived",
    validateArtifact: "Validate",
    deleteArtifactTitle: "Delete Artifact",
    deleteArtifactConfirm: "Permanently delete artifact “{name}”? This removes its directory from disk and cannot be undone.",
    artifactUsability: "Adapter File Validation",
    adapterBaseModel: "Adapter Base Model",
    close: "Close",
    collapseList: "Collapse List",
    expandList: "Expand List",
    copyPath: "Copy Path",
    copyInferenceArgs: "Copy Inference Args",
    finalAdapterHint: "The final LoRA adapter for inference validation or merging.",
    checkpointHint: "A training checkpoint for recovery or comparison.",
    mergedModelHint: "A full Transformers model directory created by merging an adapter back into its base model.",
    mergePublish: "Export Full Model",
    mergePublishHint: "Merge the selected LoRA adapter into the original base model and write a standalone Transformers model directory.",
    mergeBaseModel: "Original Base Model",
    mergeOutputDir: "Output Directory",
    mergeDtype: "Merge Dtype",
    autoResolveBaseModel: "Resolve from training record or current model config",
    autoOutputDir: "Leave blank to write under outputs/localtune/merged",
    trustRemoteCode: "Trust remote model code",
    startMergePublish: "Merge and Export",
    startedAt: "Started At",
    finishedAt: "Finished At",
    metricsRunHint: "LocalTune metrics file for loss, learning rate, and training curves.",
    artifactHint: "Local training artifact.",
    canRunInference: "Inference Ready",
    sourceReliability: "Source Record",
    relatedTrainingTask: "Related Training Task",
    artifactTrainingSource: "Training Source",
    noSourceRecordDetail: "This artifact does not record which training run produced it.",
    trainingContext: "Training Context",
    weakRelationHint: "No source recorded.",
    exactRelationHint: "This artifact records its training source.",
    runId: "Run ID",
    runMode: "Run Mode",
    runStatus: "Run Status",
    runFinishedAt: "Finished At",
    datasetProfile: "Training Dataset",
    runtimeConfig: "Runtime Config",
    inferredRelation: "No Source Record",
    exactRelation: "Source Recorded",
    trainingParamSummary: "Training Param Summary",
    metricsSummary: "Metrics Summary",
    logPreview: "Log Preview",
    viewHere: "View Here",
    config: "Config",
    trainData: "Training Set",
    valData: "Validation Set",
    testData: "Test Set",
    learningRate: "Learning Rate",
    batchSize: "Batch Size",
    epochs: "Epochs",
    estimatedVram: "Estimated VRAM",
    loraAlpha: "LoRA alpha",
    noManifest: "No producing training run recorded",
    hasManifest: "Training source recorded",
    status_unknown: "Unknown",
    status_running: "Running",
    status_stopping: "Stopping",
    status_idle: "Idle",
    status_completed: "Completed",
    status_failed: "Failed",
    status_cancelled: "Cancelled",
    status_stopped: "Stopped",
  },
};

export const navItems = [
  ["overview", Activity],
  ["models", Boxes],
  ["corpus", Database],
  ["training", Rocket],
  ["artifacts", Archive],
  ["inference", WandSparkles],
  ["history", History],
  ["environment", Settings],
];

export const paramHelp = {
  mode: "试运行用于小批量验证；正式训练使用完整训练配置。",
  model_id: "选择 Transformers 兼容的基础模型目录；模型来源不限，GGUF 文件不能作为当前微调基础模型。",
  branch: "选择模型加载方式。当前正式支持 bnb4，也就是 PEFT + bitsandbytes NF4 QLoRA。",
  dataset_profile: "训练使用的训练语料集，来自 configs/model_config.yaml 的 data.profiles。",
  max_steps: "最大训练步数。20 步适合约 20 分钟小批量验证；-1 通常表示按 epoch 训练。",
  max_seq_length: "单条样本最大 token 长度。越大越吃显存，也越能保留长上下文。",
  lora_r: "LoRA 秩。更大表达能力更强，但显存和训练时间会上升；留空则使用配置文件里的默认值。",
  gradient_accumulation_steps: "梯度累积步数。显存有限时可增大它来模拟更大 batch。",
  logging_steps: "多少 step 记录一次日志和 loss。数值越小，监控越细。",
  save_steps: "多少 step 保存一次 checkpoint。正式训练建议不要太小，避免产物过多。",
  resume_from_checkpoint: "可选。默认会开启一次新训练；选择已有 checkpoint 后，会从该保存点继续训练。",
};
